HomeWeb/Controllers/AmigosController.cs
using HomeBase;
using HomeDBEntity;
using HomeDBEntity.Enum;
using HomeService;
using HomeWeb.Models.Atributos;
using HomeWeb.Models.Enum;
using HomeWeb.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HomeWeb.Controllers
{
    public class AmigosController : MasterController
    {
        // GET: Amigo
        [Permissao(eAcessoId.Amigos, ePermissaoId.Gerenciar)]
        public ActionResult Index()
        {
            CAmizadesViewModel Amigos = new CAmizadesViewModel();
            using (AmizadeService amizadeService = new AmizadeService())
            {
                Amigos.Amizades = amizadeService.ObterAmigos().mToViewModel<CAmizadeViewModel>();
            }
            return this.RenderView(model: Amigos);
        }

        [Permissao(eAcessoId.Amigos, ePermissaoId.Pesquisar)]
        public JsonResult Pesquisar(string Query)
        {

            var data = Query.Split('|');
            Query = data[0];
            eTipoPesquisa tipoPesquisa = (eTipoPesquisa)Convert.ToInt32(data[1]);

            switch (tipoPesquisa)
            {
                case eTipoPesquisa.Search:
                    using (UsuarioService usuarioService = new UsuarioService())
                    {
                        CPesquisasViewModel pesquisa = new CPesquisasViewModel
                        {
                            Objetos = usuarioService.Obter(x => x.Usuario1.Contains(Query) && x.Id != UsuarioService.Atual.Id).mToViewModel<CUsuarioViewModel>().ToPesquisaViewModel<CPesquisaViewModel>(true),
                        };


                        var r = new CJSONMensagemModel
                        {
                            status = eEstadoModel.Pesquisa,
                            JSONModel = pesquisa

                        }.ToJsonResult();
                        return r;
                    }
                case eTipoPesquisa.Dropdown:
                    break;
            }

            return new CJSONMensagemModel
            {
                url = Url.Action(CViewModel.ActionAnterior, CViewModel.ControllerAnterior),
                status = eEstadoModel.ErrorUrl,
                mensagem = new CMensagemModel
                {
                    erro = new CErroModel
                    {
                        Mensagem = "Houve um erro ao tentar pesquisar"
                    }
                }
            }.ToJsonResult();

            
        }

        [HttpGet]
        public ActionResult VisualizaSolicitacaoAmizade()
        {
            CAmizadesViewModel model = new CAmizadesViewModel();

            using (AmizadeService amizadeService = new AmizadeService())
            {
                model.Amizades = amizadeService.ObterSolicitacoesAmizade().mToViewModel<CAmizadeViewModel>();
                if (UsuarioService.Atual.DetalheUsuario.ContadorSolicitacaoAmizade > 0)
                {
                    amizadeService.ResetarContadorAmizade();
                    var data = UsuarioService.Atual;
                    data.DetalheUsuario.ContadorSolicitacaoAmizade = 0;
                    (new SessaoService<Usuario>()).InserirSessao(data, "User");
                }
            }
            return this.RenderView(model: model);
        }

        [Permissao(eAcessoId.Amigos, ePermissaoId.Exibir)]
        public JsonResult ModalVisualizar(int id)
        {

            CAmizadeViewModel model;
            using (AmizadeService amizadeService = new AmizadeService())
            {
                model = amizadeService.ObterAmigo(id)?.mToViewModel<CAmizadeViewModel>();
            }
            if (model == null)
            {
                model = new CAmizadeViewModel();
                using (UsuarioService amizadeService = new UsuarioService())
                {
                    model.Usuario = amizadeService.ObterPorId(id).mToViewModel<CUsuarioViewModel>();
                }
            }

            return new CJSONModel
            {
                status = eEstadoModel.View,
                view = this.RenderPartialView(model: model)
            }.ToJsonResult();
        }
        [HttpGet]
        public JsonResult ModalExcluir(List<int> Id)
        {
            CUsuariosViewModel amizade = new CUsuariosViewModel();
            using (UsuarioService usuarioService = new UsuarioService())
            {
                amizade.Usuarios = usuarioService.ObterPorIds(Id.ToArray()).mToViewModel<CUsuarioViewModel>();
            }
            return new CJSONModel
            {
                status = eEstadoModel.View,
                view = this.RenderPartialView(model: amizade)
            }.ToJsonResult();
        }
        [HttpPost]
        [Permissao(eAcessoId.Amigos, ePermissaoId.Excluir)]
        public JsonResult ModalExcluir(CAmizadesViewModel model)
        {
          
            using (AmizadeService amizadeService = new AmizadeService())
            {
                amizadeService.DesfazerAmizade(model.Id.ToArray());
            }
            return new CJSONMensagemModel
            {
                status = eEstadoModel.SucessoUrl,
                url = Url.Action(CViewModel.ActionAnterior, CViewModel.ControllerAnterior),
                mensagem = new CMensagemModel
                {
                    sucesso = new CSucessoModel
                    {
                        Mensagem = "Sucesso ao desfazer a(s) amizade(s)."
                    }
                }
            }.ToJsonResult();
        }
        [HttpGet]
        public JsonResult ModalCriar()
        {

            return new CJSONModel
            {
                status = eEstadoModel.View,
                view = this.RenderPartialView()
            }.ToJsonResult();
        }
        [HttpPost]
        [Permissao(eAcessoId.Amigos, ePermissaoId.Excluir)]
        public JsonResult ModalCriar(CAmizadesViewModel model)
        {
            CUsuariosViewModel amizade = new CUsuariosViewModel();
            using (AmizadeService amizadeService = new AmizadeService())
            {
                amizadeService.DesfazerAmizade(model.Id.ToArray());
            }
            return new CJSONMensagemModel
            {
                status = eEstadoModel.Sucesso,
                mensagem = new CMensagemModel
                {
                    sucesso = new CSucessoModel
                    {
                        Mensagem = "Sucesso ao desfazer a(s) amizade(s)."
                    }
                }
            }.ToJsonResult();
        }




        [HttpPost]
        [Permissao(eAcessoId.Amigos, ePermissaoId.Inserir)]
        public JsonResult SolicitarAmizade(int id)
        {
            using (AmizadeService amizadeService = new AmizadeService())
            {
                amizadeService.SolicitarAmizade(id);
                return new CJSONMensagemModel
                {
                    status = eEstadoModel.Sucesso,
                    mensagem = new CMensagemModel
                    {
                        sucesso = new CSucessoModel
                        {
                            Mensagem = "Sucesso ao solicitar amizade!"
                        }
                    }
                }.ToJsonResult();
            }
        }
        [HttpPost]
        [Permissao(eAcessoId.Amigos, ePermissaoId.Inserir)]
        public JsonResult DesfazerSolicitacaoAmizade(int id)
        {
            using (AmizadeService amizadeService = new AmizadeService())
            {
                amizadeService.DesfazerSolicitacaoAmizade(id);
                return new CJSONMensagemModel
                {
                    status = eEstadoModel.Sucesso,
                    mensagem = new CMensagemModel
                    {
                        sucesso = new CSucessoModel
                        {
                            Mensagem = "Solicitação desfeita!"
                        }
                    }
                }.ToJsonResult();
            }
        }
        [HttpGet]
        [Permissao(eAcessoId.Amigos, ePermissaoId.Editar)]
        public JsonResult ModalConfirmarAmizade(List<int> Id)
        {
            using (UsuarioService amizadeService = new UsuarioService())
            {
                var model = new CUsuariosViewModel
                {
                    Usuarios = amizadeService.ObterPorIds(Id.ToArray()).mToViewModel<CUsuarioViewModel>()
                };
                return new CJSONMensagemModel
                {
                    status = eEstadoModel.View,
                    view = this.RenderPartialView(model: model)
                }.ToJsonResult();
            }
        }
        [HttpPost]
        [Permissao(eAcessoId.Amigos, ePermissaoId.Editar)]
        public JsonResult ModalConfirmarAmizade(CAmizadesViewModel model)
        {
            using (AmizadeService amizadeService = new AmizadeService())
            {
                amizadeService.ConfirmarAmizade(model.Id);
                return new CJSONMensagemModel
                {
                    url = Url.Action(CViewModel.ActionAnterior, CViewModel.ControllerAnterior),
                    status = eEstadoModel.SucessoUrl,
                    mensagem = new CMensagemModel
                    {
                        sucesso = new CSucessoModel
                        {
                            Mensagem = "Sucesso ao confirmar amizade!"
                        }
                    }
                }.ToJsonResult();
            }
        }
        [HttpGet]
        [Permissao(eAcessoId.Amigos, ePermissaoId.Excluir)]
        public JsonResult ModalRecusarAmizade(List<int> Id)
        {
            using (UsuarioService amizadeService = new UsuarioService())
            {
                var model = new CUsuariosViewModel
                {
                    Usuarios = amizadeService.ObterPorIds(Id.ToArray()).mToViewModel<CUsuarioViewModel>()
                };

HomeWeb/Views/Amigos/Index.cshtml
@model HomeWeb.Models.ViewModel.CAmizadesViewModel
@using HomeDBEntity.Enum;
@using HomeDBEntity.Helper;


@{
    Layout = "~/Views/Master/Menu.cshtml";
}

<title>Amigos</title>

<div id="master">
    <div class=" container">
        <div class="ui stackable grid">
            @foreach (var amigo in Model.Amizades)
            {
                <div class="four wide column">
                    @if (amigo.IdAmigo == HomeService.UsuarioService.Atual.Id && amigo.IdEstadoAmizade == eEstadoAmizade.Amigos)
                    {
                        <div class="ui ItemPulse card column selctObject" v-on:click="InsertId(@amigo.IdUsuario,$event)" data-selected="true" data-id="@amigo.IdAmigo">
                            <div class="content">
                                <i class="right floated icon"></i>
                                <img class="right floated mini ui image" src="~/Content/Home/Anonimo.png">
                                <div class="header">
                                    @amigo.Usuario.Usuario1
                                </div>
                                <div class="meta">
                                    <span>@amigo.IdEstadoAmizade.Descricao()</span>
                                </div>
                                <div class="description">
                                    @amigo.Usuario.Usuario1 (Criar status)
                                </div>
                            </div>

                        </div>
                    }
                    else if (amigo.IdEstadoAmizade == eEstadoAmizade.Amigos)
                    {
                        <div class="ui ItemPulse card column selctObject" v-on:click="InsertId(@amigo.IdAmigo,$event)" data-selected="true" data-id="@amigo.IdAmigo">
                            <div class="content">
                                <i class="right floated icon"></i>
                                <img class="right floated mini ui image" src="~/Content/Home/Anonimo.png">
                                <div class="header">
                                    @amigo.Usuario1.Usuario1
                                </div>
                                <div class="meta">
                                    <span>@amigo.IdEstadoAmizade.Descricao()</span>
                                </div>
                                <div class="description">
                                    @amigo.Usuario1.Usuario1 (Criar status)
                                </div>
                            </div>

                        </div>
                    }
                </div>
            }
        </div>
    </div>
    <div class=" btnGroupAction ui sticky" id="vGroupButtons">
        @if (HomeService.UsuarioService.PossuiAcesso(eAcessoId.Amigos, ePermissaoId.Gerenciar))
        {
            <div class="ui buttons" v-bind:class="vColor">
                <div class="ui button" :data-id="vId" v-bind:class="Habilitar" v-on:click="Click" :data-url="vUrl" :data-view="vView" v-on:ready="vUrl='@Url.Action("ModalVisualizar", "Amigos")'" id="btnDropdownButton"><i class="icon" v-bind:class="vIcon"></i>{{vName}}</div>
                <div class="ui top right pointing combo dropdown icon button">
                    <i class="dropdown icon"></i>
                    <div class="menu">
                        @if (HomeService.UsuarioService.PossuiAcesso(eAcessoId.Amigos, ePermissaoId.Exibir))
                        {
                            <div class="item dropdownButtonItem" v-on:click="Redirect('@Url.Action("VisualizaSolicitacaoAmizade", "Amigos")',$event)" data-view="page" data-allowClick="true" data-icon="search" data-color="blue" data-name="Visualizar solicitações de amizade"><i class="search icon"></i>Visualizar solicitações de amizade</div>
                        }
                        @if (HomeService.UsuarioService.PossuiAcesso(eAcessoId.Amigos, ePermissaoId.Excluir))
                        {
                            <div class="item dropdownButtonItem" v-on:click="Redirect('@Url.Action("ModalExcluir", "Amigos")',$event)" data-view="" data-allowMultiple="true" data-icon="delete" data-color="red" data-name="Desfazer amizade"><i class="delete icon"></i>Desfazer amizade</div>
                        }
                        @if (HomeService.UsuarioService.PossuiAcesso(eAcessoId.Amigos, ePermissaoId.Exibir))
                        {
                            <div class="item dropdownButtonItem " v-on:click="Redirect('@Url.Action("ModalVisualizar", "Amigos")',$event)" data-view="" data-allowMultiple="false" data-icon="search" data-color="blue" data-name="Visualizar"><i class="search icon"></i>Visualizar</div>
                        }

                    </div>
                </div>
            </div>
        }
    </div>
    <div id="modal">

    </div>
</div>

@section footer{
    <script src="~/Scripts/Base/StringBuilderScript.js"></script>
    <script src="~/Scripts/Base/DropDownScript.js"></script>
    <script src="~/Scripts/Amigos/AmigosScript.js"></script>
    <script src="~/Scripts/Base/CheckBoxScript.js"></script>

}

HomeWeb/Views/Amigos/ModalConfirmarAmizade.cshtml
@model HomeWeb.Models.ViewModel.CUsuariosViewModel

<div class="ui basic longer modal">
    <div class="content">
        <form class="ui form formModal" id="formModalConfirmarAmizade" data-url="@Url.Action("ModalConfirmarAmizade","Amigos")" method="post">
            @if (Model.Usuarios.Count == 1)
            {
                <h3 class="ui dividing inverted header">Confirma a solicitação de amizade com @Model.Usuarios.First().Usuario1?</h3>
                <input type="hidden" name="Id" value="@Model.Usuarios.First().Id" />
            }
            else
            {
                <h3 class="ui dividing inverted header">Confirma as solicitações de amizades abaixo?</h3>
                foreach (var usuario in Model.Usuarios)
                {
                    <p>@usuario.Usuario1</p>
                    <input type="hidden" value="@usuario.Id" name="Id" />
                }
            }
        </form>
    </div>
    <div class="actions" id="divFormButtons">
        <button class="ui approve button green inverted" type="button" form="formModalConfirmarAmizade" name="Confirmar">Confirmar</button>
        <button class="ui deny button red basic inverted" type="button" name="Cancelar" id="btnCancelar">Cancelar</button>
    </div>
</div>

HomeWeb/Views/Amigos/ModalCriar.cshtml
@model HomeWeb.Models.ViewModel.CAgendaViewModel

<div class="ui basic longer modal">
    <div class="content">
        <form class="ui form formModal" id="formModalAdd" data-url="@Url.Action("ModalCriar","Amigos")" method="post">
            <h3 class="ui dividing inverted header">Criar Evento</h3>
            <div class="field">
                @*<div class="ui fluid search dropdown">
                        <input class="search"/>
                    </div>*@
                <div class="field" id="divFormComparilhamento">
                    <select class="ui fluid search dropdown " multiple=""></select>
                </div>
            </div>
        </form>
    </div>
    <div class="actions" id="divFormButtons">
        <button class="ui approve button green  inverted" type="button" form="formModalAdd" name="Adicionar">Adicionar</button>
        <button class="ui deny button red basic inverted" type="button" name="Cancelar" id="btnCancelar">Cancelar</button>
    </div>

    <script src="~/Scripts/Base/CheckBoxScript.js"></script>
</div>

HomeWeb/Views/Amigos/ModalExcluir.cshtml
@model HomeWeb.Models.ViewModel.CUsuariosViewModel

<div class="ui basic longer modal">
    <div class="content">
        <form class="ui form formModal" id="formModalExcluir" data-url="@Url.Action("ModalExcluir","Amigos")" method="post">
            @if (Model.Usuarios.Count == 1)
            {
                <h3 class="ui dividing inverted header">Deseja realmente desfazer a amizade com @Model.Usuarios.First().Usuario1?</h3>
                <input type="hidden" name="Id" value="@Model.Usuarios.First().Id" />
            }
            else
            {
                <h3 class="ui dividing inverted header">Deseja realmente desfazer a amizade dos seguintes usuaros?</h3>
                foreach (var usuario in Model.Usuarios)
                {
                    <p>@usuario.Usuario1</p>
                    <input type="hidden" value="@usuario.Id" name="Id" />
                }
            }
        </form>
    </div>
    <div class="actions" id="divFormButtons">
        <button class="ui approve button red inverted" type="button" form="formModalExcluir" name="Remover">Remover</button>
        <button class="ui deny button green basic inverted" type="button" name="Cancelar" id="btnCancelar">Cancelar</button>
    </div>
</div>

HomeWeb/Views/Amigos/ModalRecusarAmizade.cshtml
@model HomeWeb.Models.ViewModel.CUsuariosViewModel

<div class="ui basic longer modal">
    <div class="content">
        <form class="ui form formModal" id="formModalModalRecusarAmizade" data-url="@Url.Action("ModalRecusarAmizade","Amigos")" method="post">
            @if (Model.Usuarios.Count == 1)
            {
                <h3 class="ui dividing inverted header">Deseja realmente recusar a solicitação de amizade de @Model.Usuarios.First().Usuario1?</h3>
                <input type="hidden" name="Id" value="@Model.Usuarios.First().Id" />
            }
            else
            {
                <h3 class="ui dividing inverted header">Deseja realmente recusar as solicitações de amizades abaixo?</h3>
                foreach (var usuario in Model.Usuarios)
                {
                    <p>@usuario.Usuario1</p>
                    <input type="hidden" value="@usuario.Id" name="Id" />
                }
            }
        </form>
    </div>
    <div class="actions" id="divFormButtons">
        <button class="ui approve button red inverted" type="button" form="formModalModalRecusarAmizade" name="Recusar">Recusar</button>
        <button class="ui deny button green basic inverted" type="button" name="Cancelar" id="btnCancelar">Cancelar</button>
    </div>
</div>

HomeWeb/Views/Amigos/ModalVisualizar.cshtml
@model HomeWeb.Models.ViewModel.CAmizadeViewModel

<div class="ui basic longer modal">
    <div class="content">
        <form class="ui form formModal" id="formAmizadeSolicitar" data-url="@Url.Action("SolicitarAmizade","Amigos")" method="post">
            <h3 class="ui dividing inverted header">Visualizar usuario</h3>
          @if (Model.Usuario.Id == HomeService.UsuarioService.Atual.Id)
          {
            <input type="hidden" name="id" value="@Model.Usuario1.Id" />
            <div class="ui two fields">
                <div class="field ">
                    <div class="field ">
                        <div class="image" href="#">
                            <img src="~/Content/Home/Anonimo.png">
                        </div>
                    </div>
                </div>
                <div class="field" id="divFormNomeEvento">
                    <label>Nome</label>
                    <p>@Model.Usuario1.Usuario1</p>
                </div>
            </div>
          }
          else
          {
            <input type="hidden" name="id" value="@Model.Usuario.Id" />
            <div class="ui two fields">
                <div class="field ">
                    <div class="field ">
                        <div class="image" href="#">
                            <img src="~/Content/Home/Anonimo.png">
                        </div>
                    </div>

                </div>
                <div class="field" id="divFormNomeEvento">
                    <label>Nome</label>
                    <p>@Model.Usuario.Usuario1</p>
                </div>
            </div>
          }

            <h4 class="ui dividing inverted header">Informações adicionais</h4>
            @switch (Model.IdEstadoAmizade)
            {
                case HomeDBEntity.Enum.eEstadoAmizade.AguardandoSolicitacao:
                    <div class="field ">
                        <div class="field" id="divFormDescricao">
                            <label>Você solicitou amizade para este usuario</label>
                        </div>
                    </div>
                    break;
                case HomeDBEntity.Enum.eEstadoAmizade.Amigos:
                    <div class="field ">
                        <div class="field" id="divFormDescricao">
                            <label>Você e @Model.Usuario.Usuario1 são amigos</label>
                        </div>
                    </div>
                    break;
            }


            <div class="ui inverted divider"></div>
        </form>
    </div>
    <div class="actions" id="divFormButtons">
        @if (Model.IdEstadoAmizade == HomeDBEntity.Enum.eEstadoAmizade.Nenhum)
            {
            <button class="ui approve button green basic inverted" type="button" name="Editar" form="formAmizadeSolicitar">Solicitar amizade</button>
        }
        @*else if (Model.IdEstadoAmizade == HomeDBEntity.Enum.eEstadoAmizade.AguardandoSolicitacao)
        {
            <button class="ui approve button red basic inverted" type="button" name="Editar" form="formAmizadeSolicitar">Cancelar solicitação de amizade</button>
        }*@
                <button class="ui deny button yellow basic inverted" type="button" name="Cancelar" id="btnCancelar">Voltar</button>
    </div>

</div>

HomeWeb/Views/Amigos/VisualizaSolicitacaoAmizade.cshtml
@model HomeWeb.Models.ViewModel.CAmizadesViewModel
@using HomeDBEntity.Enum;
@using HomeDBEntity.Helper;

@{
    Layout = "~/Views/Master/Menu.cshtml";
}

<title>Visualizar Solicitacões de Amizade</title>
<div id="master">
    <div class=" container">
        <div class="ui grid six column cards">
        @foreach (var soclicitacao in Model.Amizades)
            {
                <div class="ui ItemPulse card column selctObject" v-on:click="InsertId(@soclicitacao.IdUsuario,$event)" data-selected="true" data-id="@soclicitacao.IdUsuario">
                    <div class="content">
                        <i class="right floated icon"></i>
                        <img class="right floated mini ui image" src="~/Content/Home/Anonimo.png">
                        <div class="header">
                          @soclicitacao.Usuario.Usuario1
                        </div>
                        <div class="meta">
                            <span>@soclicitacao.IdEstadoAmizade.Descricao()</span>
                        </div>
                        <div class="description">
                            @soclicitacao.Usuario.Usuario1 (Criar status)
                        </div>
                    </div>
                    @*<div class="extra content">
                        <div class="ui one buttons">
                            <div class="ui basic red button">Recusar amizade</div>
                        </div>
                    </div>*@
                </div>
            }
        </div>
    </div>
   
    <div class=" btnGroupAction ui sticky" id="vGroupButtons">
        @if (HomeService.UsuarioService.PossuiAcesso(eAcessoId.Amigos, ePermissaoId.Gerenciar))
            {
            <div class="ui buttons" v-bind:class="vColor">
                <div class="ui button" :data-id="vId" v-bind:class="Habilitar" v-on:click="Click" :data-url="vUrl" :data-view="vView" v-on:ready="vUrl='@Url.Action("Index", "Amigos")'" id="btnDropdownButton"><i class="icon" v-bind:class="vIcon"></i>{{vName}}</div>
                <div class="ui top right pointing combo dropdown icon button">
                    <i class="dropdown icon"></i>
                    <div class="menu">
                        @if (HomeService.UsuarioService.PossuiAcesso(eAcessoId.Amigos, ePermissaoId.Exibir))
                        {
                            <div class="item dropdownButtonItem" v-on:click="Redirect('@Url.Action("Index", "Amigos")',$event)" data-view="page" data-allowClick="true" data-icon="search" data-color="blue"  data-name="Votar para pagina de amizade"><i class="search icon"></i>Votar para pagina de amizade</div>
                        }
                        @if (HomeService.UsuarioService.PossuiAcesso(eAcessoId.Amigos, ePermissaoId.Excluir))
                        {
                            <div class="item dropdownButtonItem" v-on:click="Redirect('@Url.Action("ModalRecusarAmizade", "Amigos")',$event)" data-view="" data-icon="delete" data-allowMultiple="true" data-color="red" data-name="Recusar amizade"><i class="delete icon"></i>Recusar amizade</div>
                        }
                        @if (HomeService.UsuarioService.PossuiAcesso(eAcessoId.Amigos, ePermissaoId.Inserir))
                        {
                            <div class="item dropdownButtonItem" v-on:click="Redirect('@Url.Action("ModalConfirmarAmizade", "Amigos")',$event)" data-view="" data-icon="add" data-color="green" data-allowMultiple="true" data-name="Aceitar amizade"><i class="add icon"></i>Aceitar amizade</div>
                        }
                        @if (HomeService.UsuarioService.PossuiAcesso(eAcessoId.Amigos, ePermissaoId.Exibir))
                        {
                            <div class="item dropdownButtonItem " v-on:click="Redirect('@Url.Action("ModalVisualizar", "Amigos")',$event)" data-view="" data-icon="search" data-color="blue" data-allowMultiple="false" data-name="Visualizar"><i class="search icon"></i>Visualizar</div>
                        }

                    </div>
                </div>
            </div>
        }
    </div>
</div>

<div id="Modaldiv">
    <modalShow></modalShow>
</div>
@section footer{
    <script src="~/Scripts/Base/StringBuilderScript.js"></script>
    <script src="~/Scripts/Base/DropDownScript.js"></script>
    <script src="~/Scripts/Amigos/AmigosScript.js"></script>
    <script src="~/Scripts/Base/CheckBoxScript.js"></script>

}