HomeWeb/Controllers/AgendaController.cs
using HomeWeb.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using HomeWeb;
using HomeWeb.Models.Atributos;
using static HomeWeb.Helper;
using HomeService;
using HomeDBEntity.Enum;
using HomeDBEntity;
using HomeBase;
using HomeWeb.Models.Enum;

namespace HomeWeb.Controllers
{
    public class AgendaController : MasterController
    {
        [Permissao(eAcessoId.Agenda, ePermissaoId.Exibir)]
        public ActionResult Index()
        {
            List<CAgendaViewModel> model = new List<CAgendaViewModel>();
            using (AgendaService agendaService = new AgendaService())
            {
                model.AddRange(agendaService.ObterPorUsuario(UsuarioService.Atual).mToViewModel<CAgendaViewModel>());

            }

            var agendas = new CAgendasViewModel()
            {
                Agendas = model
            };
            return View(agendas);
        }

        [Permissao(eAcessoId.Agenda, ePermissaoId.Pesquisar)]
        public JsonResult Pesquisar(string Query)
        {
            var data = Query.Split('|');
            Query = data[0];
            eTipoPesquisa tipoPesquisa = (eTipoPesquisa)Convert.ToInt32(data[1]);

            switch (tipoPesquisa)
            {
                case eTipoPesquisa.Search:
                    using (AgendaService agendaservice = new AgendaService())
                    {
                        CPesquisasViewModel pesquisa = new CPesquisasViewModel
                        {
                            Objetos = agendaservice.ObterPorTitulo(Query).mToViewModel<CAgendaViewModel>().ToPesquisaViewModel<CPesquisaViewModel>(true),
                        };


                        var r = new CJSONMensagemModel
                        {
                            status = eEstadoModel.Pesquisa,
                            JSONModel = pesquisa

                        }.ToJsonResult();
                        return r;
                    }
                case eTipoPesquisa.Dropdown:
                    using (AmizadeService usuarioService = new AmizadeService())
                    {
                        var datavm = usuarioService.ObterAmigos().mToViewModel<CAmizadeViewModel>();
                        List<CUsuarioViewModel> r = new List<CUsuarioViewModel>();
                        foreach (var d in datavm)
                        {
                            if (d.IdUsuario == UsuarioService.Atual.Id)
                            {
                                r.Add(d.Usuario1.mToViewModel<CUsuarioViewModel>());
                            }
                            else
                            {
                                r.Add(d.Usuario.mToViewModel<CUsuarioViewModel>());
                            }
                        }
                        CPesquisasViewModel pesquisa = new CPesquisasViewModel
                        {
                            Objetos = r.ToPesquisaViewModel<CPesquisaViewModel>(true)
                        };

                        return new CJSONMensagemModel
                        {
                            status = eEstadoModel.Pesquisa,
                            JSONModel = pesquisa

                        }.ToJsonResult();
                    }
            }

            return new CJSONMensagemModel
            {
                url = Url.Action(CViewModel.ActionAnterior, CViewModel.ControllerAnterior),
                status = eEstadoModel.ErrorUrl,
                mensagem = new CMensagemModel
                {
                    erro = new CErroModel
                    {
                        Mensagem = "Houve um erro ao tentar pesquisar"
                    }
                }
            }.ToJsonResult();

        }

        [HttpGet]
        public JsonResult ModalCriarAgenda()
        {

            return new CJSONMensagemModel
            {
                view = this.RenderPartialView(),
                status = eEstadoModel.View,
                tipoView = eTipoView.Modal
            }.ToJsonResult();
        }
        [HttpPost]
        [Permissao(eAcessoId.Agenda, ePermissaoId.Inserir)]
        public JsonResult ModalCriarAgenda(CAgendaViewModel model)
        {

            if (!model.DiaInteiro)
            {
                model.Fim = model.DataFim.AddHours(model.HoraFim.Hour).AddMinutes(model.HoraFim.Minute);
            }
            model.Inicio = model.DataInicio.AddHours(model.HoraInicio.Hour).AddMinutes(model.HoraInicio.Minute);
            model.IdUsuario = UsuarioService.Atual.Id;

            Agenda agenda = model.mToViewModel<Agenda>();

            if (model.postAmigos != null)
            {
                foreach (var idAmigo in model.postAmigos)
                {
                    agenda.AgendaCompartilhada.Add(new AgendaCompartilhada
                    {
                        IdUsuario = idAmigo
                    });
                }
            }


            try
            {
                using (AgendaService agendaService = new AgendaService())
                {
                    agendaService.Inserir(agenda);
                }

                return (new CJSONMensagemModel
                {
                    url = CViewModel.UrlAnterior,
                    mensagem = new CMensagemModel
                    {
                        sucesso = new CSucessoModel
                        {
                            Mensagem = $"Sucesso ao criar o evento {agenda.NomeEvento}"

                        }
                    },
                    status = eEstadoModel.SucessoUrl
                }).ToJsonResult();
            }
            catch (Exception ex)
            {
                return (new CJSONMensagemModel
                {
                    url = CViewModel.UrlAnterior,
                    mensagem = new CMensagemModel
                    {
                        erro = new CErroModel
                        {
                            Mensagem = ex.Message,
                            Titulo = "Erro ao criar um novo evento",
                            Stack = ex.StackTrace
                        }
                    },
                    status = eEstadoModel.ErrorUrl
                }).ToJsonResult();
            }


        }
        [HttpGet]
        [Permissao(eAcessoId.Agenda, ePermissaoId.Exibir)]
        public JsonResult ModalVisualizarAgenda(List<int> Id)
        {
            CAgendaViewModel agenda;
            using (AgendaService agendaService = new AgendaService())
            {
                var aux = agendaService.ObterPorId(Id.First());
                agenda = aux.mToViewModel<CAgendaViewModel>();
                //agenda.AgendaCompartilhada = aux.Usuario1.ToViewModel<CAgendaViewModel>();
                //using(AmizadeService amizadeService = new AmizadeService())
                //{
                //    agenda.Amigos = amizadeService.ObterAmigos().Where(x=> agenda.AgendaCompartilhada.Select(y => y.IdUsuario).Contains(x.IdAmigo)).ToViewModel<CAmizadeViewModel>();
                //}
                //agenda = new CAgendaViewModel
                //{
                //    NomeEvento = aux.NomeEvento,
                //    DataFim = aux.Fim.Value.Date,
                //    DataInicio = aux.Inicio.Date,
                //    Local = aux.Local,
                //    Descricao = aux.Descricao,
                //    DiaInteiro = aux.DiaInteiro,
                //    Lembrete = aux.Lembrete.Value,
                //    Inicio = aux.Inicio,
                //    Fim = aux.Fim,
                //    IdUsuario = aux.IdUsuario,
                //    Amigos = aux.AgendaCompartilhada.Select(x => new CAmizadeViewModel
                //    {
                //        Usuario = x.Usuario.ToViewModel<CUsuarioViewModel>(),

                //        IdAmigo = x.IdUsuario,
                //        IdUsuario = UsuarioService.Atual.Id,

                //    }).ToList()
                //};
            }
            return new CJSONMensagemModel
            {
                view = this.RenderPartialView(model: agenda),
                status = eEstadoModel.View,
                tipoView = eTipoView.Modal
            }.ToJsonResult();
        }
        [HttpGet]
        public JsonResult ModalExcluirAgenda(List<int> Id)
        {
            List<CAgendaViewModel> agenda = new List<CAgendaViewModel>();
            using (AgendaService agendaService = new AgendaService())
            {
                foreach (var id in Id)
                {
                    agenda.Add(agendaService.ObterPorId(id).mToViewModel<CAgendaViewModel>());
                }
            }

            CAgendasViewModel model = new CAgendasViewModel
            {
                Agendas = agenda
            };

            return new CJSONMensagemModel
            {
                view = this.RenderPartialView(model: model),
                status = eEstadoModel.View,
                tipoView = eTipoView.Modal
            }.ToJsonResult();
        }
        [HttpPost]
        [Permissao(eAcessoId.Agenda, ePermissaoId.Excluir)]
        public JsonResult ModalExcluirAgenda(CAgendasViewModel model)
        {

            try
            {
                using (AgendaService agendaService = new AgendaService())
                {
                    agendaService.Remover(x => x.IdUsuario == UsuarioService.Atual.Id && model.Ids.Contains(x.Id));
                    var dataAgenda = agendaService.ObterPorIds(model.Ids.ToArray()).Where(x => x.IdUsuario != UsuarioService.Atual.Id && model.Ids.Contains(x.Id));
                    agendaService.Descompartilhar(dataAgenda.Select(x => x.Id).ToArray());
                }

                return (new CJSONMensagemModel
                {
                    url = CViewModel.UrlAnterior,
                    mensagem = new CMensagemModel
                    {
                        sucesso = new CSucessoModel

HomeWeb/Controllers/BugController.cs
using HomeBase;
using HomeDBEntity.Enum;
using HomeService;
using HomeWeb.Models.Atributos;
using HomeWeb.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HomeWeb.Controllers
{
    public class BugController : Controller
    {
        // GET: Bug
        public ActionResult Index()
        {

            CBugsViewModel model = new CBugsViewModel();
            using (BugService bugService = new BugService())
            {
                model.Bugs = bugService.Rank().mToViewModel<CBugViewModel>();
            }
            return View(model);
        }

        [HttpGet]
        [Permissao(eAcessoId.Bug, ePermissaoId.Excluir)]
        public JsonResult ModalResolverBug(int cod)
        {

            CBugViewModel model = null;
            using (BugService bugService = new BugService())
            {
                model = bugService.ObterPorCodigo(cod).ToViewModel<CBugViewModel>();
            }

            return new CJSONMensagemModel
            {
                status = eEstadoModel.View,
                tipoView = eTipoView.Modal,
                view = this.RenderPartialView(model: model)
            }.ToJsonResult();
        }

        [HttpPost]
        [Permissao(eAcessoId.Bug, ePermissaoId.Excluir)]
        public JsonResult ModalResolverBug(CBugViewModel model)
        {

            using (BugService bugService = new BugService())
            {
                bugService.Remover(x => x.CodigoBug == model.CodigoBug);
            }


            return new CJSONMensagemModel
            {
                url = CViewModel.UrlAnterior,
                status = eEstadoModel.SucessoUrl,
                mensagem = new CMensagemModel
                {
                    sucesso = new CSucessoModel
                    {
                        Mensagem = "Problema resolvido com sucesso!"
                    }
                }
            }.ToJsonResult();
        }
    }
}

HomeWeb/Controllers/ChatController.cs
using HomeDBEntity.Enum;
using HomeWeb.Models.Atributos;
using System.Web.Mvc;
using HomeBase;
using HomeService;

namespace HomeWeb.Controllers
{
    public class ChatController : MasterController
    {
        [Permissao(eAcessoId.Chat, ePermissaoId.Exibir)]
        public ActionResult Index()
        {
            
            return View();
        }

        [Permissao(eAcessoId.Chat,ePermissaoId.Inserir)]
        public JsonResult EnviarMensagem()
        {
            return new CJSONMensagemModel
            {
                status = eEstadoModel.Sucesso,

            }.ToJsonResult();
        }
    }
}

HomeWeb/Controllers/PainelController.cs
using HomeDBEntity.Enum;
using HomeWeb.Models.Atributos;
using System.Web.Mvc;

namespace HomeWeb.Controllers
{
    public class PainelController : MasterController
    {
        [HttpGet]
        [Permissao(eAcessoId.Painel, ePermissaoId.Gerenciar)]
        public ActionResult Index()
        {
            return View();
        }

        //[HttpGet]
        //public ActionResult Configuracoes()
        //{
        //    return RedirectToAction("Index", "Configuracoes");
        //}
    }
}

HomeWeb/Views/Master/Layout.cshtml
@using System.Web.Optimization;

<link rel="shortcut icon" href="~/Content/Home/HomeIco.ico">

@RenderBody()


@Styles.Render("~/Content/css")
@Scripts.Render("~/bundles/Basico")

@RenderSection("footer")

HomeWeb/Views/Master/Menu.cshtml
@using HomeDBEntity.Enum;
@{
    Layout = "~/Views/Master/Layout.cshtml";
}

<div class="ui stackable  menu inverted">
    <a class="item" href="@Url.Action("Index","Painel")">
        <i class="ui big icon home"></i>
    </a>
    @if (HomeService.UsuarioService.PossuiAcesso(eAcessoId.Agenda, ePermissaoId.Exibir))
    {
        if (HomeService.UsuarioService.ObterContadorAgendaCompartilhada() > 0)
        {
            <div data-tooltip="Você possui @HomeService.UsuarioService.ObterContadorAgendaCompartilhada() novo(s) compartilhamento(s) de agenda(s)." data-position="bottom center" data-variation="tiny">
                <a class="item" href="@Url.Action("Index","Agenda")">
                    <i class="ui big icon calendar"></i>
                    <i class="ui right corner icon inverted info circle"></i>
                </a>
            </div>

        }
        else
        {
            <a class="item" href="@Url.Action("Index","Agenda")">
                <i class="ui big icon calendar"></i>
            </a>
        }
    }
    @if (HomeService.UsuarioService.PossuiAcesso(eAcessoId.Amigos, ePermissaoId.Exibir))
    {
        if (HomeService.UsuarioService.ObterContadorSolicitacaoAmizade() > 0)
        {
            <div data-tooltip="Você possui @HomeService.UsuarioService.ObterContadorSolicitacaoAmizade() novas solicitações de amizade." data-position="bottom center" data-variation="tiny">
                <a class="item" href="@Url.Action("Index", "Amigos")">
                    <i class="big icons">
                        <i class="ui users icon"></i>
                        <i class="corner inverted info circle icon"></i>
                    </i>
                </a>
            </div>

        }
        else
        {
            <a class="item" href="@Url.Action("Index", "Amigos")">
                <i class="ui big icon users"></i>
            </a>
        }
    }
    @if (HomeService.UsuarioService.PossuiAcesso(eAcessoId.Chat, ePermissaoId.Gerenciar))
    {
        <a class="item" href="@Url.Action("Index","Chat")">
            <i class="ui big icon Wechat"></i>
        </a>
    }
    <div class="right menu">
        @if (HomeService.UsuarioService.PossuiAcesso(ePermissaoId.Pesquisar))
        {
            <div class="item">
                <div class="ui small search ">
                    <div class="ui trasnparent  icon input">
                        <input class="prompt" type="text" placeholder="Pesquisar...">
                        <i class="search icon"></i>
                    </div>
                    <div class="results"></div>
                </div>
            </div>
        }
        <div class="ui dropdown item">
            <i class="icon big user"></i>
            <div class="menu">
                @if (HomeService.UsuarioService.PossuiAcesso(eAcessoId.Perfil, ePermissaoId.Exibir))
                {
                    <a class="item" href="@Url.Action("Perfis", "Perfil")"><i class="big icon book"></i>Perfils</a>
                    <div class="divider"></div>
                }
                @if (HomeService.UsuarioService.PossuiAcesso(eAcessoId.Usuario, ePermissaoId.Exibir))
                {
                    <a class="item" href="@Url.Action("Usuarios", "Usuario")"><i class="big icon users"></i>Usuarios</a>
                    <div class="divider"></div>
                }
                @if (HomeService.UsuarioService.PossuiAcesso(eAcessoId.Configuracao, ePermissaoId.Exibir))
                {
                    <a class="item" href="@Url.Action("Configuracoes","Configuracao")"><i class="big icon settings"></i>Configurações</a>
                    <div class="divider"></div>
                }
                @if (HomeService.UsuarioService.PossuiAcesso(eAcessoId.Bug, ePermissaoId.Exibir))
                {
                    <a class="item" href="@Url.Action("Index","Bug")"><i class="big icon bug"></i>Bugs</a>
                    <div class="divider"></div>
                }
                <a class="item" href="@Url.Action("Logout","Login")"><i class="big icon sign out"></i>Logout</a>
            </div>
        </div>
    </div>
</div>



@section footer{

    @RenderSection("footer")
    @Scripts.Render("~/bundles/Menu")

    <script src="~/signalr/hubs"></script>
    <script src="~/Scripts/Base/SignalRScript.js"></script>


}

@RenderBody()