HomeWeb/Models/ViewModel/Perfil/AcessoViewModel.cs
using HomeDBEntity;
using HomeDBEntity.Atributos;
using HomeWeb.Models.Atributos;
using System;
using System.Collections.Generic;

namespace HomeWeb.Models.ViewModel
{
    [Cast(typeof(Acesso))]
    public class CAcessoViewModel
    {
        public CAcessoViewModel(Acesso acesso)
        {
            Codigo = acesso.Codigo;
            Nome = acesso.Nome;
        }

        public CAcessoViewModel()
        { }
        [Pesquisa(eCampoNome.Valor)]
        public int Codigo { get; set; }
        [Pesquisa(eCampoNome.Nome)]
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public List<CPermissaoViewModel> Permissoes { get; set; } = new List<CPermissaoViewModel>();
        public bool Marcado { get; set; }
        public List<string> PermissoesPost { get; internal set; }
    }
}

HomeWeb/Models/ViewModel/Perfil/PerfilViewModel.cs
using System.Collections.Generic;

namespace HomeWeb.Models.ViewModel
{
    public class CPerfilViewModel : CViewModel
    {
        public int Codigo { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }

        public List<CAcessoViewModel> Acessos { get; set; }
        public List<string> AcessosPost { get; set; }
        public List<CUsuarioViewModel> Usuarios { get; set; }
        public List<int> UsuariosPost { get; set; }
    }
}

HomeWeb/Models/ViewModel/Perfil/PerfisViewModel.cs
using System.Collections.Generic;

namespace HomeWeb.Models.ViewModel
{
    public class CPerfisViewModel
    {
        public List<CPerfilViewModel> Perfis { get; set; }
        public List<CAcessoViewModel> Acessos { get; set; }
        public List<CPermissaoViewModel> Permissoes { get; set; }
    }
}

HomeWeb/Models/ViewModel/Perfil/PermissaoViewModel.cs
using HomeDBEntity;
using HomeDBEntity.Atributos;
using System;

namespace HomeWeb.Models.ViewModel
{
    [Cast(typeof(Permissao))]
    public class CPermissaoViewModel
    {
        public CPermissaoViewModel(Permissao permissao)
        {
            Codigo = permissao.Codigo;
            Nome = permissao.Nome;
        }

        public CPermissaoViewModel() { }

        public int Codigo { get; set; }
        public string Nome { get; set; }
        public bool Marcado { get; set; }
        public string Descricao { get; set; }
    }
}

HomeWeb/Controllers/PerfilController.cs
using HomeDBEntity;
using HomeService;
using HomeWeb.Models.Atributos;
using System.Linq;
using System.Web.Mvc;
using System;
using HomeWeb.Models.ViewModel;
using static HomeWeb.Helper;
using System.Threading.Tasks;
using System.Collections.Generic;
using HomeDBEntity.Helper;
using System.Text;
using HomeDBEntity.Enum;

namespace HomeWeb.Controllers
{
    public class PerfilController : MasterController
    {
        [Permissao(eAcessoId.Perfil, ePermissaoId.Exibir)]
        public ActionResult Perfis()
        {
            if (UsuarioService.PossuiAcesso("Perfil.Gerenciar"))
                return View(ObterPerfis());
            else
                return View(ObterPerfisUsuario());
        }

        #region Grids
        [HttpGet]
        public PartialViewResult GridPerfil(CPerfisViewModel model)
        {
            return PartialView(model);
        }
        [HttpGet]
        public PartialViewResult GridAcesso(CPerfisViewModel model)
        {
            return PartialView(model);
        }
        [HttpGet]
        public PartialViewResult GridPermissao(CPerfisViewModel model)
        {
            return PartialView(model);
        }
        #endregion


        #region Modal

        #region Perfil

        #region Criar
        [HttpGet]
        public JsonResult ModalCriarPerfil()
        {
            List<CPermissaoViewModel> listaPermissao;
            List<CAcessoViewModel> listaAcesso;

            using (PermissaoService permissaoService = new PermissaoService())
            {
                listaPermissao = permissaoService.ObterTodos().Select(x => new CPermissaoViewModel
                {
                    Codigo = x.Codigo,
                    Descricao = x.Descricao,
                    Nome = x.Nome
                }).ToList();
            }


            using (AcessoService acessoService = new AcessoService())
            {
                listaAcesso = acessoService.ObterTodos().Select(x => new CAcessoViewModel
                {
                    Codigo = x.Codigo,
                    Descricao = x.Descricao,
                    Nome = x.Nome,
                    Permissoes = listaPermissao
                }).ToList();
            }

            if (listaAcesso.IsNullOrEmpty())
            {
                return Helper.ToJsonResult(new CJsonViewModel()
                {
                    status = HomeService.Enum.eTipoMensagem.Error,
                    mensagem = new CMensagemViewModel
                    {
                        status = HomeService.Enum.eTipoMensagem.Error,
                        erro = new CErroViewModel()
                        {
                            Mensagem = "Não há acessos para associar a um novo perfil.",
                            Titulo = "Associação indisponivél."
                        }
                    }
                });
            }

            CPerfilViewModel perfilViewModel = new CPerfilViewModel()
            {
                Acessos = listaAcesso
            };

            return (new CJsonViewModel()
            {
                view = this.RenderPartialView(model: perfilViewModel),
                status = HomeService.Enum.eTipoMensagem.View
            }).ToJsonResult();

        }
        [HttpPost]
        [Permissao(eAcessoId.Perfil,ePermissaoId.Inserir)]
        public JsonResult ModalCriarPerfil(CPerfilViewModel model)
        {
            if (model.AcessosPost.IsNullOrEmpty())
            {
                return Helper.ToJsonResult(new CJsonViewModel()
                {
                    status = HomeService.Enum.eTipoMensagem.Error,
                    mensagem = new CMensagemViewModel
                    {
                        status = HomeService.Enum.eTipoMensagem.Error,
                        erro = new CErroViewModel()
                        {
                            Mensagem = "Não é possivel criar um novo perfil sem associar a um acesso",
                            Titulo = "Houve um erro ao criar um novo perfil",

                        }
                    }
                });
            }

            try
            {
                Perfil perfil = model.mToViewModel<Perfil>();
                perfil.AssociacaoPerfil = new List<AssociacaoPerfil>();

                using (AcessoService acessoService = new AcessoService())
                {
                    using (PermissaoService permissaoService = new PermissaoService())
                    {
                        var dataAcessos = acessoService.ObterPorNomes(model.AcessosPost.Select(x => x.Split('.')[0]).GroupBy(x => x).Select(x => x.First()).ToArray());
                        foreach (var acesso in dataAcessos)
                        {
                            var dataPermissao = permissaoService.ObterPorNomes(model.AcessosPost.Where(x => x.Contains(acesso.Nome)).Select(x => x.Split('.')[1]).GroupBy(x => x).Select(x => x.First()).ToArray());
                            foreach (var permissao in dataPermissao)
                            {
                                perfil.AssociacaoPerfil.Add(new AssociacaoPerfil
                                {
                                    CodigoAcesso = acesso.Codigo,
                                    CodigoPermissao = permissao.Codigo
                                });
                            }
                        }
                    }
                }

                using (PerfilService perfilService = new PerfilService())
                {
                    perfilService.Inserir(perfil);
                }

                //es.CriarAssociar(perfil);
                return Helper.ToJsonResult(new CJsonViewModel()
                {
                    status = HomeService.Enum.eTipoMensagem.SucessoUrl,
                    mensagem = new CMensagemViewModel
                    {
                        sucesso = new CSucessoViewModel()
                        {
                            Mensagem = $"Sucesso ao criar o perfil {model.Nome}"
                        }
                    },
                    url = Url.Action(CViewModel.ActionAnterior, CViewModel.ControllerAnterior)

                });
            }
            catch (Exception ex)
            {

                return Helper.ToJsonResult(new CJsonViewModel()
                {
                    status = HomeService.Enum.eTipoMensagem.ErrorUrl,
                    mensagem = new CMensagemViewModel
                    {
                        erro = new CErroViewModel
                        {
                            Mensagem = $"Erro ao criar o perfil {model.Nome}",
                            Stack = ex.StackTrace,
                            Titulo = "Erro"
                        },
                        status = HomeService.Enum.eTipoMensagem.ErrorUrl
                    },
                    url = Url.Action(CViewModel.ActionAnterior, CViewModel.ControllerAnterior),

                });
            }

        }



        #endregion

        #region Editar
        [HttpGet]
        public JsonResult ModalEditarPerfil(int cod)
        {

            var pR = new PerfilRepository();
            Perfil perfil;

            using (PerfilRepository perfilrepository = new PerfilRepository())
            {
                perfil = pR.ObterPorCodigo(cod);
            }

            List<CAcessoViewModel> acessos;
            using (AcessoService acessoService = new AcessoService())
            {
                acessos = acessoService.ObterTodos().mToViewModel<CAcessoViewModel>();
            }

            List<CPermissaoViewModel> permissoes;
            using (PermissaoService permissaoService = new PermissaoService())
            {
                permissoes = permissaoService.ObterTodos().mToViewModel<CPermissaoViewModel>();

            }

            foreach (var item in acessos)
            {
                item.Permissoes = permissoes;
            }

            List<string> lp = new List<string>();

            var ps = perfil.AssociacaoPerfil;
            foreach (var item in ps)
            {
                lp.Add($"{acessos.FirstOrDefault(x => x.Codigo == item.CodigoAcesso)?.Nome}.{permissoes.FirstOrDefault(x => x.Codigo == item.CodigoPermissao)?.Nome}");
            }

            CPerfilViewModel perVM = new CPerfilViewModel()
            {
                Codigo = perfil.Codigo,
                Nome = perfil.Nome,
                Acessos = acessos,
                Descricao = perfil.Descricao,
                AcessosPost = lp
            };

            return Helper.ToJsonResult(new CJsonViewModel()
            {
                view = Helper.RenderPartialView(this, model: perVM),
                status = HomeService.Enum.eTipoMensagem.View,
            });

        }
        [HttpPost]
        [Permissao(eAcessoId.Perfil,ePermissaoId.Editar)]
        public JsonResult ModalEditarPerfil(CPerfilViewModel model)
        {

            try
            {

                var acessosPost = model.AcessosPost?.ToArray();
                List<Acesso> acessos = new List<Acesso>();
                using (AcessoService As = new AcessoService())
                {
                    if (acessosPost != null)
                    {
                        using (PermissaoService Ps = new PermissaoService())
                        {
                            acessos = As.ObterPorNomes(acessosPost.Select(x => x.Split('.')[0]).ToArray());
                            Parallel.ForEach(acessos, (acesso) =>
                            {
                                acesso.Permissoes = Ps.ObterPorNomes(acessosPost.Where(x => x.Contains(acesso.Nome)).Select(x => x.Split('.')[1]).ToArray());
                            });
                        }
                    }
                }



                Perfil perfil = new Perfil()
                {
                    Acessos = acessos,
                    Codigo = model.Codigo,

HomeWeb/Views/Perfil/CriarPerfil.cshtml
@{
    Layout = "~/Views/Master/Menu.cshtml";
}

@model HomeWeb.Models.ViewModel.CPerfilViewModel

<title>Criar perfil</title>


<form class="ui form formCadastro" id="formModalAdd" data-url="@Url.Action("ModalCriarPerfil","Perfil")" method="post">
    <h3 class="ui dividing inverted header">Criar perfil</h3>
    <div class="field">
        <div class="two fields">
            <div class="field" id="divFormNome">
                <label>Nome</label>
                <input type="text" name="Nome" placeholder="Nome" />
            </div>
            <div class="field" id="divFormCodigo">
                <label>Codigo</label>
                <input type="number" name="Codigo" placeholder="Codigo" />
            </div>
        </div>
    </div>
    <div class="ui inverted divider"></div>
    <h3 class="ui dividing inverted header">Acessos e permissões</h3>

    <div class="DropdownAcessoPermissao field">
        <div class="three fields campo">
            <div class="divAcessos field">
                <div class="ui selection dropdown">
                    <input type="hidden" name="Permissao">
                    <i class="dropdown icon"></i>
                    <div class="default text">Permissao</div>
                    <div class="menu">
                        @foreach (var acesso in Model.Acessos)
                        {
                            <div class="item" data-value="@acesso.Codigo">@acesso.Nome</div>
                        }
                    </div>
                </div>
            </div>
            <div class="divPermissoes field">
                <div class="ui field dropdownPermissao" id="dropdownPermissao" name="Permissoes">
                    <div class="ui selection dropdown">
                        <input type="hidden" name="Permissao">
                        <i class="dropdown icon"></i>
                        <div class="default text">Permissao</div>
                        <div class="menu">
                            @foreach (var permissao in Model.Permissoes)
                            {
                                <div class="item" data-value="@permissao.Codigo">@permissao.Nome</div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="field">
        <div class="ui list">
            <div class="item">
                <i class="folder icon"></i>
                <div class="content">
                    <div class="header"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="field">
        <input type="button" class="ui icon plus button inverted basic green" id="mais" value="Adicionar acesso" />
    </div>
    <div class="ui inverted divider"></div>
    <button class="ui button green  inverted" type="button" form="formModalAdd" name="Adicionar" id="btnSubmit">Adicionar</button>
    <button class="ui button red basic inverted" type="button" name="Voltar" id="btnCancelar">Voltar</button>
</form>



@section footer{

}

HomeWeb/Views/Perfil/GridAcesso.cshtml
@model HomeWeb.Models.ViewModel.CPerfisViewModel
@using HomeDBEntity.Enum;
<table class="ui selectable inverted table">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Descriçao</th>
            @if (HomeService.UsuarioService.PossuiAcesso(eAcessoId.Perfil,ePermissaoId.Gerenciar))
            {
                <th>Codigo</th>
                <th>Ações</th>
            }
        </tr>
    </thead>
    <tbody>
        @foreach (var acesso in Model.Acessos)
        {
            <tr>
                <td class="Nome">@acesso.Nome</td>
                <td class="Descricao"> @acesso.Descricao</td>
                @if (HomeService.UsuarioService.PossuiAcesso(eAcessoId.Perfil, ePermissaoId.Gerenciar))
                {
                    <td class="Codigo"> @acesso.Codigo </td>
                    <td class="collapsing">
                        <div>
                            @if (HomeService.UsuarioService.PossuiAcesso(eAcessoId.Perfil, ePermissaoId.Excluir))
                            {
                                <input type="button" class="ui button inverted red modalCall" data-url="@Url.Action("ModalExcluirAcesso", "Perfil", new { cod = acesso.Codigo })" name="Excluir" value="Excluir" id="btnModalExcluir" />
                            }
                            @if (HomeService.UsuarioService.PossuiAcesso(eAcessoId.Perfil, ePermissaoId.Editar))
                            {
                                <input type="button" class="ui button inverted yellow modalCall" data-url="@Url.Action("ModalEditarAcesso", "Perfil", new { cod = acesso.Codigo })" name="Editar" value="Editar" id="btnModalEditar" />
                            }
                        </div>
                    </td>
                }
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <th colspan="3">Total de acessos: @Model.Acessos.Count</th>
            @if (HomeService.UsuarioService.PossuiAcesso(eAcessoId.Perfil, ePermissaoId.Inserir))
            {
                <th>
                    <input type="button" class="ui button inverted green modalCall" data-url="@Url.Action("ModalCriarAcesso", "Perfil")" name="Criar" value="Criar" id="btnModalCriar" />
                </th>
            }
        </tr>
    </tfoot>
</table>

HomeWeb/Views/Perfil/GridPermissao.cshtml
@model HomeWeb.Models.ViewModel.CPerfisViewModel
@using HomeDBEntity.Enum;

<table class="ui selectable inverted table">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Descriçao</th>
            @if (HomeService.UsuarioService.PossuiAcesso(eAcessoId.Perfil, ePermissaoId.Gerenciar))
            {
                <th>Codigo</th>
                <th>Ações</th>
            }
        </tr>
    </thead>
    <tbody>
        @foreach (var permissao in Model.Permissoes)
            {
            <tr>
                <td class="Nome">@permissao.Nome</td>
                <td class="Descricao"> @permissao.Descricao</td>
                @if (HomeService.UsuarioService.PossuiAcesso(eAcessoId.Perfil, ePermissaoId.Gerenciar))
                {
                    <td class="Codigo"> @permissao.Codigo </td>
                        <td class="collapsing">
                            <div>
                                @if (HomeService.UsuarioService.PossuiAcesso(eAcessoId.Perfil, ePermissaoId.Excluir))
                                {
                                    <input type="button" class="ui button inverted red modalCall" data-url="@Url.Action("ModalExcluirPermissao", "Perfil", new { cod = permissao.Codigo })" name="Excluir" value="Excluir" id="btnModalExcluir" />
                                }
                                @if (HomeService.UsuarioService.PossuiAcesso(eAcessoId.Perfil, ePermissaoId.Editar))
                                {
                                    <input type="button" class="ui button inverted yellow modalCall" data-url="@Url.Action("ModalEditarPermissao", "Perfil", new { cod = permissao.Codigo })" name="Editar" value="Editar" id="btnModalEditar" />
                                }
                            </div>
                        </td>
                }
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <th colspan="3">Total de permissoes: @Model.Permissoes.Count</th>
            @if (HomeService.UsuarioService.PossuiAcesso(eAcessoId.Perfil, ePermissaoId.Inserir))
            {
                <th>
                    <input type="button" class="ui button inverted green modalCall" data-url="@Url.Action("ModalCriarPermissao", "Perfil")" name="Criar" value="Criar" id="btnModalCriar" />
                </th>
            }
        </tr>

    </tfoot>
</table>

HomeWeb/Views/Perfil/ModalAssociarPerfil.cshtml
@model HomeWeb.Models.ViewModel.CPerfilViewModel

<div class="ui basic longer modal">
    <div class="scrolling content">
        <form class="ui form formModal" id="formModalAssociar" data-url="@Url.Action("ModalAssociarPerfil","Perfil")" method="post">
            <h3 class="ui dividing inverted header">Deseja associar o perfil "@Model.Nome" a quais contas?</h3>
            <div class="field">
                <div class="ui celled relaxed list">
                    <div class="item FatherList">
                        <div class="list">
                            @foreach (var usuario in Model.Usuarios)
                            {
                                <div class="item">
                                    <div class="ui child checkbox ChildList">
                                        @if (Model.UsuariosPost.Contains(usuario.Id))
                                        {
                                            <input type="checkbox" name="UsuariosPost" value="@usuario.Id" >
                                        }
                                        else
                                        {
                                            <input type="checkbox" name="UsuariosPost" value="@usuario.Id" checked>
                                        }
                                        <label>@usuario.Nome</label>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
            <input type="hidden" name="Codigo" value="@Model.Codigo" />
        </form>
    </div>
    <div class="actions" id="divFormButtons">
        <button class="ui approve button blue inverted" type="button" form="formModalAssociar" name="Associar">Associar</button>
        <button class="ui deny button red basic inverted" type="button" name="Cancelar" id="btnCancelar">Cancelar</button>
    </div>
    <script src="~/Scripts/Base/CheckBoxScript.js"></script>
</div>

HomeWeb/Views/Perfil/ModalCriarAcesso.cshtml
@model HomeWeb.Models.ViewModel.CAcessoViewModel

<div class="ui basic longer modal">
    <div class="content">
        <form class="ui form formModal" id="formModalAdd" data-url="@Url.Action("ModalCriarAcesso","Perfil")" method="post">
            <h3 class="ui dividing inverted header">Criar Acesso</h3>
            <div class="field">
                <div class="field" id="divFormNome">
                    <label>Nome</label>
                    <input type="text" name="Nome" placeholder="Nome" />
                </div>
            </div>
            <div class="field">
                <div class="field" id="divFormNome">
                    <label>Descrição</label>
                    <input type="text" name="Descricao" placeholder="Descrição" />
                </div>
            </div>
        </form>
    </div>
    <div class="actions" id="divFormButtons">
        <button class="ui approve button green  inverted" type="button" form="formModalAdd" name="Adicionar">Adicionar</button>
        <button class="ui deny button red basic inverted" type="button" name="Cancelar" id="btnCancelar">Cancelar</button>
    </div>
    <script src="~/Scripts/Base/CheckBoxScript.js"></script>
</div>

HomeWeb/Views/Perfil/ModalCriarPerfil.cshtml
@model HomeWeb.Models.ViewModel.CPerfilViewModel
@using MvcCheckBoxList.Model;

<div class="ui basic longer modal">
    <div class="scrolling content">
        <form class="ui form formModal" id="formModalAdd" data-url="@Url.Action("ModalCriarPerfil","Perfil")" method="post">
            <h3 class="ui dividing inverted header">Criar perfil</h3>
            <div class="field">
                <div class="field" id="divFormNome">
                    <label>Nome</label>
                    <input type="text" name="Nome" placeholder="Nome" />
                </div>
            </div>
            <div class="field">
                <div class="field" id="divFormNome">
                    <label>Descrição</label>
                    <input type="text" name="Descricao" placeholder="Descrição" />
                </div>
            </div>
            <h3 class="ui dividing inverted header">Acessos</h3>
            <div class="scrolling content">
                <div class="field">
                    <div class="ui celled relaxed list">
                        @foreach (var acesso in Model.Acessos)
                        {
                        <div class="item FatherList">
                            <div class="ui master checkbox MasterList">
                                <input type="checkbox" name="Acessos" nome="@acesso.Nome">
                                <label>@acesso.Nome</label>
                            </div>
                            <div class="list">
                                @foreach (var permissao in acesso.Permissoes)
                                    {
                                    <div class="item">
                                        <div class="ui child checkbox ChildList">
                                            <input type="checkbox" name="AcessosPost" value="@acesso.Nome.@permissao.Nome">
                                            <label>@permissao.Nome</label>
                                        </div>
                                    </div>
                                    }
                            </div>
                        </div>
                        }
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="actions" id="divFormButtons">
        <button class="ui approve button green  inverted" type="button" form="formModalAdd" name="Adicionar">Adicionar</button>
        <button class="ui deny button red basic inverted" type="button" name="Cancelar" id="btnCancelar">Cancelar</button>
    </div>
    <script src="~/Scripts/Base/CheckBoxScript.js"></script>
</div>

HomeWeb/Views/Perfil/ModalCriarPermissao.cshtml
@model HomeWeb.Models.ViewModel.CPermissaoViewModel

<div class="ui basic longer modal">
    <div class="content">
        <form class="ui form formModal" id="formModalAdd" data-url="@Url.Action("ModalCriarPermissao","Perfil")" method="post">
            <h3 class="ui dividing inverted header">Criar Permissão</h3>
            <div class="field">
                <div class="field" id="divFormNome">
                    <label>Nome</label>
                    <input type="text" name="Nome" placeholder="Nome" />
                </div>
            </div>
            <div class="field">
                <div class="field" id="divFormNome">
                    <label>Descrição</label>
                    <input type="text" name="Descricao" placeholder="Descrição" />
                </div>
            </div>
        </form>
    </div>
    <div class="actions" id="divFormButtons">
        <button class="ui approve button green  inverted" type="button" form="formModalAdd" name="Adicionar">Adicionar</button>
        <button class="ui deny button red basic inverted" type="button" name="Cancelar" id="btnCancelar">Cancelar</button>
    </div>
    <script src="~/Scripts/Base/CheckBoxScript.js"></script>
</div>

HomeWeb/Views/Perfil/ModalEditarPerfil.cshtml
@model HomeWeb.Models.ViewModel.CPerfilViewModel

<div class="ui basic longer modal">
    <div class="scrolling content">
        <form class="ui form formModal" id="formModalEditar" data-url="@Url.Action("ModalEditarPerfil","Perfil")" method="post">
            <h3 class="ui dividing inverted header">Editar perfil</h3>
            <div class="field">
                <div class="field" id="divFormNome">
                    <label>Nome</label>
                    <input type="text" name="Nome" placeholder="Nome" value="@Model.Nome" />
                    <input type="hidden" value="@Model.Codigo" name="Codigo" />
                </div>
                <div class="field">
                    <div class="field" id="divFormNome">
                        <label>Descrição</label>
                        <input type="text" name="Descricao" placeholder="Descrição" value="@Model.Descricao" />
                    </div>
                </div>
                <h3 class="ui dividing inverted header">Acessos</h3>
                <div class="scrolling content">
                    <div class="field">
                        <div class="ui celled relaxed list">
                            @foreach (var acesso in Model.Acessos)
                            {
                                <div class="item FatherList">
                                    <div class="ui master checkbox MasterList">
                                        <input type="checkbox" name="Acessos" nome="@acesso.Nome">
                                        <label>@acesso.Nome</label>
                                    </div>
                                    <div class="list">
                                        @foreach (var permissao in acesso.Permissoes)
                                        {
                                            <div class="item">
                                                <div class="ui child checkbox ChildList">
                                                    @if (Model.AcessosPost.Contains(acesso.Nome + "." + permissao.Nome))
                                                    {
                                                        <input type="checkbox" name="AcessosPost" value="@acesso.Nome.@permissao.Nome" checked>
                                                    }
                                                    else
                                                    {
                                                        <input type="checkbox" name="AcessosPost" value="@acesso.Nome.@permissao.Nome">
                                                    }
                                                    <label>@permissao.Nome</label>
                                                </div>
                                            </div>
                                        }
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="actions" id="divFormButtons">
        <button class="ui approve button yellow  inverted" type="button" form="formModalEditar" name="Editar">Editar</button>
        <button class="ui deny button red basic inverted" type="button" name="Cancelar" id="btnCancelar">Cancelar</button>
    </div>
    <script src="~/Scripts/Base/CheckBoxScript.js"></script>
</div>

HomeWeb/Views/Perfil/ModalExcluirAcesso.cshtml
@model HomeWeb.Models.ViewModel.CAcessoViewModel

<div class="ui basic longer modal">
    <div class="content">
        <form class="ui form formModal" id="formModalExcluir" data-url="@Url.Action("ModalExcluirAcesso","Perfil")" method="post">
            <h3>Deseja realmente excluir o acesso "@Model.Nome" e suas dependências?</h3>
            <div class="ui inverted divider"></div>
            <input type="hidden" name="Codigo" value="@Model.Codigo" />
        </form>
    </div>
    <div class="actions" id="divFormButtons">
        <button class="ui approve button red inverted" type="button" form="formModalExcluir" name="Remover">Remover</button>
        <button class="ui deny button green basic inverted" type="button" name="Cancelar" id="btnCancelar">Cancelar</button>
    </div>
</div>